config/routes.rb
SimpleCi::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :projects do
    resources :builds do
      member do
        get :details
      end
    end
    
    member do
      get :enqueue, :preferences, :check_status
    end
  end
  
  root :to => 'projects#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/build.rb
require "bunny"

class Build < ActiveRecord::Base
  attr_accessible :output, :duration, :failed_tests, :pending_tests, :succeeded_tests
  
  include AASM
  
  belongs_to :project
  
  # we should enqueue build only after it's fully changed its state (e.g. will have aasm_state attribute set to 'enqueued')
  # so worker script could find it and invoke `run!` properly (otherwise transision errors)
  after_commit :enqueue_task, on: :update, if: lambda {|build| build.enqueued? }
    
  aasm do
    state :created, :initial => true
    state :enqueued
    state :running
    state :deploying
    state :failure
    state :success
  
    event :enqueue do      
      transitions :from => [:created, :failure, :success], :to => :enqueued
    end
    
    event :run do
      transitions :from => :enqueued, :to => :running
    end
    
    event :succeed do      
      transitions :from => [:running, :deploying], :to => :success
    end
    
    event :fail do      
      transitions :from => [:enqueued, :created, :running, :deploying], :to => :failure
    end
    
    event :deploy do
      transitions :from => [:success], :to => :deploying
    end
  end
    
  def enqueue_task
    conn = Bunny.new
    conn.start

    ch   = conn.create_channel
    q    = ch.queue(DEFAULT_QUEUE, :durable => true)
    msg  = Marshal.dump build_id: self.id

    q.publish(msg, :persistent => true)
    Rails.logger.warn " [#{DEFAULT_QUEUE}] Sent #{msg}"

    conn.close
  end
  
  def tmp_dir
    File.join TMP_DIR, "project_#{self.project.id}_#{self.project.branch}"
  end
  
  def tmp_dir_with_project_name
    File.join tmp_dir, File.basename(self.project.path_to_rails_root)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :user_id, :name, :path_to_rails_root, :aasm_state, :run_bundle_before_builds, :branch, :copy_before_builds
  
  belongs_to :user
  has_many :builds
  
  validates :name, :path_to_rails_root, presence: true
  validates :path_to_rails_root, rails_project: true
  
  def state
    self.builds.order('updated_at DESC').to_a.try(:first).try(:aasm_state)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authentication::ActiveRecordHelpers

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :provider, :uid

  has_many :projects, :dependent => :nullify
  
  def create_project(options)
    Project.create(options.reverse_merge({user_id: self.id }))
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  etag { current_user.try(:id) }
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!
  
  def details
    @build = current_user.projects.find(params[:project_id]).builds.find(params[:id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    user = User.find_for_oauth(request.env["omniauth.auth"])

    if user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect user, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!
  
  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to projects_path, :notice => "Project sucessfully created" #@project
    else
      redirect_to :back, :notice => "There were errors while creating project"
    end
  end

  def update
    @project = current_user.projects.find_by!(id: params[:id])
    if @project.update_attributes(project_params)
      redirect_to projects_path, :notice => "Project sucessfully saved" #@project
    else
      redirect_to :back, :notice => "There were errors while saving project"
    end
  end
    
  def enqueue
    @project = current_user.projects.find_by!(id: params[:id])
    @project.builds.create!.enqueue!
    respond_to do |format|
      format.json { render json: @project }
      format.html { redirect_to projects_path }
    end
  rescue AASM::InvalidTransition => e
    @project.fail!
    render nothing: true
  end

  def preferences
    @project = Project.find_by!(id: params[:id])
  end
  
  def check_status
    project = Project.find params[:id]
    last_successfull_build = project.builds.where(['aasm_state = ?', 'success']).order('updated_at ASC').last
    render json: {status: project.state, reference_duration: last_successfull_build.try(:duration)}
  end

private
  def project_params
    params.require(:project).permit(:name, :path_to_rails_root, :copy_before_builds, :run_bundle_before_builds, :branch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/builds/_build.html.erb
<div class="row">
  <div class="small-2 columns <%= build.failure? ? 'alert' : 'success' %> label">build #<%= build.id %></div>
  <div class="small-6 columns">
    <% # TODO: add test stats(qty, duration, etc instead of details for build with status - success) %>
    <%= build.aasm_state %>
    <% if build.success? %>
      [duration: <%= build.duration.round(1) %> ms, succeeded: <%= build.succeeded_tests%>, pending: <%= build.pending_tests %>]
    <% elsif build.failure? %>
      [<%= link_to "Details", details_project_build_path(build.project, build) %>]
    <% else %>
      <%= nil %>
    <% end %>
  </div>
  <div class="small-4 columns">run <%= time_ago_in_words build.updated_at %> ago</div>
</div>

app/views/builds/details.html.erb
<%= link_to raw("&#x2190; Back to builds list"), projects_path(@build.project) %>

<div style="clear:both"></div>
<h3>Build #<%= @build.id %> Output</h3>

<pre><%= @build.output %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleCi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar">
  <ul class="title-area"><li class="name"></li></ul>
  <section class="top-bar-section">
    <% if current_user %>
    <ul class="left">
      <li class="has-dropdown not-click"><a href="/projects">Go to Project</a>
        <ul class="dropdown">
          <% cache 'top_menu_projects_list' do %>
          <% current_user.projects.each do |project| %>
          <li><%= link_to project.name, projects_path(project) %></li>
          <% end %>
          <% end %>
        </ul>
      </li>
    </ul>
    
    <ul class="right">
      <li class="not-click"><a href="#"><%= current_user.email %></a></li>
      <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></a>
    </ul>
    <% end %>
  </section>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<div class="row">
  <div class="large-3 columns">Name:</div>
  <div class="large-9 columns"><%= form.text_field :name %></div>
</div>

<div class="row">
  <div class="large-3 columns">Path to Rails root:<br/>Or url of Github repo</div>
  <div class="large-9 columns"><%= form.text_field :path_to_rails_root %></div>
</div>

<div class="row">
  <div class="large-3 columns">Operate on branch:</div>
  <div class="large-9 columns"><%= form.text_field :branch %></div>
</div>

<div class="row">
  <div class="large-3 columns">Run `bundle install` before build:</div>
  <div class="large-9 columns"><%= form.check_box :run_bundle_before_builds %></div>
</div>

<div class="row">
  <div class="large-3 columns">Copy to temp folder before build:</div>
  <div class="large-9 columns"><%= form.check_box :copy_before_builds %></div>
</div>

app/views/projects/_project.html.erb
<div class="row">
  <div class="small-3 columns"><%= project.name %></div>
  <div class="small-3 columns"><%= project.aasm_state %></div>
  <div class="small-3 columns"><%= link_to "Preferences", preferences_project_path(project) %></div>
  <div class="small-3 columns"><%= link_to "Run", enqueue_project_path(project), :class => "run_project button small", :remote => true %></div>
</div>

<div class="row last_build" style="display:none">
  <div class="small-2 columns label">last build</div>
  <div class="small-6 columns state">running</div>
  <div class="small-4 columns">run <%= time_ago_in_words Time.current %> ago</div>
  <div style="clear:both"></div>
  <div class="radius progress success large-8" style="display: none;"><span class="meter" style="width: 0%;"></span></div>
  </div>
</div>
  
<%= render :partial => "builds/build", collection: project.builds.order('updated_at DESC').limit(15) %>

app/views/projects/index.html.erb
<div class="row save-btn">
  <div class="large-12 columns">
    <%= link_to "Create New Project", new_project_path, class: "button" %>
  </div>
</div>

<h3>Projects</h3>

<%= render :partial => @projects %>

app/views/projects/new.html.erb
<h3 style="text-align:center">New Project</h3>

<%= form_for @project do |f| %>
  <%= render f %>
  
  <div class="row save-btn">
    <div class="large-12 columns">
      <%= f.submit "Create", class: "button" %>
    </div>
  </div>
<% end %>

app/views/projects/preferences.html.erb
<h3 style="text-align:center">Preferences</h3>

<%= form_for @project do |f| %>
  <%= render f %>
  
  <div class="row save-btn">
    <div class="large-12 columns">
      <%= f.submit "Save", class: "button" %>
    </div>
  </div>
<% end %>